### ISSUE TITLE
Add a function/config to proxy sites that restrict access on their own

### ISSUE THREAD

**Issue by Erghel** [censortracker/censortracker#464]
Collect a database of sites that restrict access for users themselves.

**Comment by meetinger** [comment]
In most cases, these are sites with a domain that ends in ".ua"

**Comment by zloirock** [comment]
@meetinger you are deluded.

**Comment by Erghel** [comment]
During all this time we have managed to collect a small register of sites, you can familiarize yourself with it here - https://github.com/roskomsvoboda/ctconf/blob/main/reverse-restrictions/ru/sites.json

**Comment by grbovic** [comment]
I'm closing this one, since duplication of #650
