### ISSUE TITLE
Временное проксирование для сайта

### ISSUE THREAD

**Issue by Twilightssuperb** [censortracker/censortracker#630]
Добавьте возможность открывать тот или иной сайт временно через прокси, минуя список проксируемых сайтов, — через кнопку в меню расширения после клика по иконке.

Насколько «временно», не знаю, надо указывать определённый промежуток при этом или хватит простого «до конца текущего сеанса» (пока запущен браузер).

**Comment by grbovic** [comment]
We already have such feature.
