### ISSUE TITLE
Krautchan.net и deviantart.com

### ISSUE THREAD

**Issue by SODIX** [censortracker/censortracker#652]
Первый грузится через раз(ERR_TUNNEL_CONNECTION_FAILED), второй выдает ошибку загрузки({ "err": "read error" }). Из РФ, даже если вписать их в список руками. Поправьте пожалуйста, мои любимые сайты.

**Comment by SODIX** [comment]
С ласт апдейтом, девиантарт стал открываться, но картинки все-равно не показываются.

**Comment by hikeri** [comment]
Добавьте в список проксируемых сайтов wixmp.com что бы отображались картинки
