### ISSUE TITLE
Добавление в ручной список из быстрого меню

### ISSUE THREAD

**Issue by gaydba** [censortracker/censortracker#653]
Сейчас, когда сайт заблокирован или сам блокирует доступ по региону, экстеншен пишет, что доступ не блокирован. 
Приходится идти в долгое меню и руками добавлять сайт в исключения.

Было бы очень удобно добавлять сайт одной кнопкой сразу из быстрого меню доступного по нажатию на экстеншен.

**Comment by msva** [comment]
НЯП, это возможно и так.
Нажимаете на гамбургер и из трёх кнопок ("авто", "всегда", "никогда") выбираете "всегда". Это добавляет сайт в ручной список проксирования.
