### ISSUE TITLE
 У Firefox вышло обновление и оно поддерживает мобильную версию расширений

### ISSUE THREAD

**Issue by frenksrok** [censortracker/censortracker#658]
Обновите и адаптируйте расширение. Будет легче жить) Спасибо) 

Уважаемые
@lk-geimfari @Piterden 
обратите внимание) 
С любовью rafaelkastar

**Comment by Erghel** [comment]
https://github.com/roskomsvoboda/censortracker/issues/645#issuecomment-1872492020
