### ISSUE TITLE
lastfm.freetls.fastly.net

### ISSUE THREAD

**Issue by TheFinalCut83** [censortracker/censortracker#659]
Есть ли в планах проксирование lastfm.freetls.fastly.net, [заблокированного позавчера](https://reestr.rublacklist.net/ru/record/6639534/) ?

**Comment by Erghel** [comment]
Реестр заблокированных сайтов, который использует расширение, обновляется, насколько мне известно, каждые 40 минут и данный домен должен был туда попасть, но так как он многоуровневый с его проксированием могла возникнуть проблема из-за чего он собственно может не работать через прокси Censor Tracker.

**Comment by TheFinalCut83** [comment]
Базу принудительно обновляю, дважды сброс настроек выполняю - всё никак. Вот он по сей час и не работает через цензортрекер... А будет ли в будущем?

**Comment by Erghel** [comment]
> Базу принудительно обновляю, дважды сброс настроек выполняю - всё никак. Вот он по сей час и не работает через цензортрекер... А будет ли в будущем?

https://registry.censortracker.org/api/v3/ct-domains/ - домен находится в базе, которую CT проксирует автоматически для региона RU. Проблема, скорее всего, связана с тем, что домен многоуровневый, как я писал выше. Будет ли работать в будущем - если удастся внедрить поддержку многоуровневых доменов, не сломал текущую работу расширения, то будет, да.
