### ISSUE TITLE
Блокировка не onion/i2p доменов на onion/i2p сайте

### ISSUE THREAD

**Issue by hikeri** [censortracker/censortracker#667]
Предлагаю добавить функцию блокирующую подключение (или пропускающее через прокси) к сайтам вне сети tor или i2p при посещении onion/i2p сайтов.

**Comment by Polycarbohydrate** [comment]
Translation for others (Google Translate):

Title of post: 

**Blocking non-onion/i2p domains on the onion/i2p site**

Content:

**I propose to add a function that blocks connections (or allows them through a proxy) to sites outside the tor or i2p network when visiting onion/i2p sites.**
