### ISSUE TITLE
Невозможно пройти Cloudflare на https://nnmclub.to в хромоподобном браузере Supermium под Windows XP

### ISSUE THREAD

**Issue by EgorKuzevanov** [censortracker/censortracker#680]
Бесконечно перезагружается страница проверки Cloudflare:
![IMG_1456](https://github.com/censortracker/censortracker/assets/78859951/03e2fa37-ed1f-421c-b75c-eab7c8268ad8)
Windows XP SP3 (x86), хромоподобный браузер Supermium 122 (https://github.com/win32ss/supermium/releases). Расширение Censor Tracker скачано из Chrome Web Store.

**Comment by dpi-detector** [comment]
1) Расширение CesorTracker не имеет никакого отношения к прохождению капчи.

Единственное, что оно делает - формирует список "запросы к такому-то домену отправлять через такой-то прокси-сервер" и передаёт этот список браузеру.
Ну и плюс совершает необходимые действия для совершения этой задачи (скачать список заблокированных сайтов и получить активный прокси-сервер, например).

Ни к каким капчам оно не имеет никаких отношений и как-либо влиять на них ему, даже если было бы желание, не даёт браузерное API

2) подобные проблемы с прохождением капчи CloudFlare, согласно наблюдениям, часто бывают при  открытии сайта по http вместо HTTPS.

3) Windows XP слишком устаревшая ОС, в которой устарело всё, вплоть до криптобиблиотек.
И никто (и скорее всего даже авторы указанного форка хромиума) не гарантирует работоспособности во всех случаях со всеми серверами.
Вполне возможно, что прохождение капчи CF проваливается в том числе и потому что сам WAF у CoudFlare считает неправдоподобным хождение на сайт в 2024 году реального человека с 20летней ОС (это только предположение основанное на опыте. достоверно выяснить это невозможно, как минимум без админского доступа к аккаунту CloudFlare на котором расположен сайт)

**Comment by dpi-detector** [comment]
впрочем, есть шанс, что деело в том, что запросы на домене сайта идут через один IP-адрес (потому что проксируются), а запросы на домены, которые подсовывает cloudflare при тестировании - через другой (не проксируются).

Но даже в этом случае задача по отлову дополнительных доменов лежит на ваших плечах. И не только не входит в полномочия плагина (он не может отличать когда надо захватывать другие домены, а когда нет, к тому же, даже если бы мог - это очень трудно реализуемо в коде), но и  трудноосуществима (по описанным выше причинам).

Однако, если для вас данная задача по отлову доменов из консоли браузера выглядит сложной - можно зайти в чат, посвящённй расширению, в телеграме и попросить там помощи у сообщества.
