### ISSUE TITLE
Проблемы с Firefox

### ISSUE THREAD

**Issue by egornovivan** [censortracker/censortracker#691]
На сайте аддонов
![изображение](https://github.com/censortracker/censortracker/assets/60801856/78425276-c2fb-4c30-889e-c139edd3e76a)

Релиз версия с гитхаба https://github.com/censortracker/censortracker/releases/download/v16.0.0/Censor_Tracker_Firefox_v16.0.0.zip.zip Не инсталится, пишет якобы поврежден.

Firefox 115.11.0esr (64-разрядный)

**Comment by grbovic** [comment]
Censor Tracker is now available in Mozilla Addons.
