### ISSUE TITLE
Не открывает rutracker.org в Firefox

### ISSUE THREAD

**Issue by kramola-RU** [censortracker/censortracker#693]
Здравствуйте!
Не открывается сайт rutracker.org
Использую Firefox 126 в Win-11
Проблема появилась два дня назад, а до этого сайт открывался нормально.

**Comment by kramola-RU** [comment]
Сегодня 10 июня сайт ру-трекер стал открываться нормально.

**Comment by grbovic** [comment]
This was related to rutracker.org itself.
