### ISSUE TITLE
Mozilla молча заблокировала в России расширение Censor Tracker для Firefox

### ISSUE THREAD

**Issue by EgorKuzevanov** [censortracker/censortracker#694]
У меня:
- нетбук Acer Aspire One ZG5 (2008 года выпуска);
- 32-битный одноядерный двухпоточный процессор Intel Atom N270 с тактовой частотой 1,6 ГГц;
- 1,5 ГБ оперативной памяти;
- встроенный графический чип Intel GMA 950 с поддержкой DirectX 9.0, Shader Model 2.0 и OpenGL 1.4;
- 32-битная версия Windows 8 Enterprise (на ядре Windows NT 6.2), выпущенная 26 октября 2012 года;
- и браузер r3dfox (форк современных версий браузера Mozilla Firefox для Windows 7/8/8.1): https://github.com/Eclipse-Community/r3dfox

Сегодня (10 июня 2024 года) я обнаружил, что компания Mozilla (разработчик браузера Mozilla Firefox) молча заблокировала на всей территории России все расширения Firefox для обхода блокировок Роскомнадзора (в том числе и расширение Censor Tracker). При попытке открыть ссылку https://addons.mozilla.org/ru/firefox/addon/censor-tracker с российских IP-адресов выскакивает ошибка "Эта страница недоступна в вашем регионе". Помогает только установка VPN (Browsec или AdGuard VPN), но это тупиковый путь, поскольку все VPN-расширения на https://addons.mozilla.org/ru/firefox тоже недоступны в России из-за вышеупомянутых мной геоблокировок со стороны Mozilla. На данный момент я живу в поселке городского типа Инской (город Белово, Кемеровская область, Россия) и у меня кузбасский интернет-провайдер [Goodline](https://goodline.info).

Уважаемые разработчики расширения Censor Tracker, вы не могли бы выложить на GitHub установочный XPI-файл Censor Tracker, предназначенный для установки в браузер Mozilla Firefox и его форк для Windows 7/8/8.1 под названием r3dfox?

**Comment by Danissimo88** [comment]
Browsec тоже не лучшее решение, мягко говоря. Российская поделка.

**Comment by grbovic** [comment]
Censor Tracker is now available in Mozilla Addons.
