### ISSUE TITLE
Сегодня 20 июня 2024 расширение перестало работать

### ISSUE THREAD

**Issue by kramola-RU** [censortracker/censortracker#701]
В первой половине дня всё работало нормально - сайты открывались.
Но во второй половине дня расширение перестало работать - ни один из заблокированных сайтов не открывается.
Использую расширение в Firefox 127 на Win11

**Comment by EJYozhenka** [comment]
Тоже самое. Пишет, что "не удалось установить соединение с прокси сервером".

Вот отладочная информация:
```
{
  "countryCode": "RU",
  "countryName": "Russia",
  "customRegistryUrl": "https://registry.ctreserve.de/api/v3/dpi/",
  "ignoreUrl": null,
  "proxyUrl": "https://app.ctreserve.de/api/proxy-config/",
  "registryUrl": "https://registry.ctreserve.de/api/v3/ct-domains/",
  "specifics": {
    "cooperationRefusedORIUrl": "https://registry.ctreserve.de/api/v3/disseminators/refused/"
  },
  "configEndpointUrl": "https://raw.githubusercontent.com/censortracker/ctconf/main/config.json",
  "configEndpointSource": "GitHub",
  "conflictingExtensions": [],
  "version": "18.2.0",
  "fallbackReason": "noMore",
  "fallbackProxyError": "NS_ERROR_UNKNOWN_PROXY_HOST",
  "fallbackProxyInUse": true,
  "browser": {
    "name": "Firefox",
    "version": "127"
  },
  "proxyLastFetchTs": 1718901027739,
  "badProxies": [],
  "currentProxyURI": {
    "proxyServerProtocol": "HTTPS",
    "proxyServerURI": "p.ctreserve.de:3319"
  },
  "proxyControlled": true
}
```

**Comment by drewaaaaa** [comment]
Похожая проблема с Firefox. Судя по всему, виноват снова Kaspersky (без него дополнение нормально работает, их модуль внедрения в https-трафик чудит, обещают к 27 июня раскатать обновление 21.18, где не будет такой проблемы). При установленном дополнении и антивирусе дополнение пишет, что "прокси-сервер не принимает соединения", если выбрать пункт "Прокси censortracker" в настройках. Если вписывать свой прокси, то начинается ерунда с PR_END_OF_FILE_ERROR и т.п.
Свой прокси у меня точно рабочий, т.к. под линухом таких проблем нет, да и сейчас без дополнения через прокси весь трафик идёт.

**Comment by kramola-RU** [comment]
У меня нет никакого каспера, но проблема есть. Вернее - была.
Сегодня (22 июня) расширение снова работает.
